import type { Product, User } from '../types';

export const seedProducts: Product[] = [
  {
    id: 'p1',
    title: 'Netflix Premium 1 Month',
    description: '4K Ultra HD, 4 screens, unlimited streaming. Private account with full warranty.',
    category: 'Streaming',
    price: 35,
    originalPrice: 50,
    image: 'netflix',
    stock: 50,
    rating: 4.9,
    reviews: 1284,
    featured: true,
    bestSeller: true,
    trending: true,
    delivery: 'Fast Delivery',
    code: 'NFLX-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p2',
    title: 'Spotify Premium 3 Months',
    description: 'Ad-free music, offline downloads, premium quality audio. 90-day warranty.',
    category: 'Streaming',
    price: 45,
    originalPrice: 60,
    image: 'spotify',
    stock: 40,
    rating: 4.8,
    reviews: 892,
    featured: true,
    bestSeller: true,
    delivery: 'Fast Delivery',
    code: 'SPTF-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p3',
    title: 'Steam Wallet $25',
    description: 'Digital gift card for Steam platform. Global region, redeem worldwide.',
    category: 'Gaming',
    price: 92,
    originalPrice: 100,
    image: 'steam',
    stock: 30,
    rating: 4.9,
    reviews: 654,
    bestSeller: true,
    delivery: 'Fast Delivery',
    code: 'STM-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p4',
    title: 'Google Play $25',
    description: 'Google Play gift card. Use on apps, games, movies, and books.',
    category: 'Gift Cards',
    price: 95,
    originalPrice: 105,
    image: 'google',
    stock: 25,
    rating: 4.7,
    reviews: 412,
    delivery: 'Fast Delivery',
    code: 'GPL-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p5',
    title: 'PlayStation Plus 12 Months',
    description: 'Full year of PS Plus Essential. Online multiplayer & monthly free games.',
    category: 'Gaming',
    price: 220,
    originalPrice: 260,
    image: 'playstation',
    stock: 15,
    rating: 4.9,
    reviews: 328,
    featured: true,
    trending: true,
    delivery: 'Fast Delivery',
    code: 'PSN-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p6',
    title: 'Xbox Game Pass Ultimate 3M',
    description: 'Hundreds of games on console, PC, and cloud. EA Play included.',
    category: 'Gaming',
    price: 180,
    originalPrice: 210,
    image: 'xbox',
    stock: 20,
    rating: 4.8,
    reviews: 276,
    delivery: 'Fast Delivery',
    code: 'XBX-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p7',
    title: 'Deezer Premium 6 Months',
    description: 'Lossless HiFi audio, offline listening, no ads for 180 days.',
    category: 'Streaming',
    price: 75,
    originalPrice: 90,
    image: 'deezer',
    stock: 35,
    rating: 4.6,
    reviews: 189,
    delivery: 'Fast Delivery',
    code: 'DZR-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p8',
    title: 'PUBG UC 660',
    description: '660 Unknown Cash for PUBG Mobile. Direct top-up to your account.',
    category: 'Top-Ups',
    price: 38,
    originalPrice: 45,
    image: 'pubg',
    stock: 100,
    rating: 4.8,
    reviews: 987,
    bestSeller: true,
    delivery: 'Fast Delivery',
    code: 'PUBG-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p9',
    title: 'Free Fire 530 Diamonds',
    description: '530 Diamonds for Free Fire. Instant account top-up.',
    category: 'Top-Ups',
    price: 32,
    originalPrice: 40,
    image: 'freefire',
    stock: 100,
    rating: 4.7,
    reviews: 543,
    delivery: 'Fast Delivery',
    code: 'FF-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p10',
    title: 'Windows 11 Pro License',
    description: 'Genuine Microsoft Windows 11 Professional. Lifetime activation key.',
    category: 'Software',
    price: 85,
    originalPrice: 120,
    image: 'windows',
    stock: 40,
    rating: 4.9,
    reviews: 231,
    featured: true,
    delivery: 'Fast Delivery',
    code: 'WIN-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p11',
    title: 'Microsoft Office 365',
    description: 'Office 365 Business. Word, Excel, PowerPoint, OneDrive, Teams.',
    category: 'Software',
    price: 110,
    originalPrice: 140,
    image: 'office',
    stock: 25,
    rating: 4.8,
    reviews: 198,
    delivery: 'Fast Delivery',
    code: 'OFC-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
  {
    id: 'p12',
    title: 'iTunes Gift Card $50',
    description: 'Apple iTunes card. Works for App Store, Apple Music, iCloud.',
    category: 'Gift Cards',
    price: 175,
    originalPrice: 195,
    image: 'apple',
    stock: 20,
    rating: 4.8,
    reviews: 412,
    delivery: 'Fast Delivery',
    code: 'APL-' + Math.random().toString(36).slice(2, 10).toUpperCase(),
  },
];

export const seedUsers: User[] = [
  {
    id: 'admin1',
    email: 'admin@yass-shop.com',
    password: 'admin123',
    name: 'Yassine Bentoumia',
    role: 'admin',
    balance: 0,
    createdAt: Date.now(),
  },
  {
    id: 'staff1',
    email: 'staff@yass-shop.com',
    password: 'staff123',
    name: 'Staff Agent',
    role: 'staff',
    balance: 0,
    createdAt: Date.now(),
  },
  {
    id: 'demo1',
    email: 'demo@yass-shop.com',
    password: 'demo123',
    name: 'Demo User',
    role: 'user',
    balance: 50,
    createdAt: Date.now(),
  },
];

export const categories = [
  { id: 'all', name: 'All Products', icon: '🛍️' },
  { id: 'Streaming', name: 'Streaming', icon: '🎬' },
  { id: 'Gaming', name: 'Gaming', icon: '🎮' },
  { id: 'Top-Ups', name: 'Top-Ups', icon: '💎' },
  { id: 'Gift Cards', name: 'Gift Cards', icon: '🎁' },
  { id: 'Software', name: 'Software', icon: '💻' },
];

// Product visual config: gradient + emoji + optional photo URL
export interface ProductVisual {
  emoji: string;
  gradient: string;
  bgColor: string;
  accent: string;
  photo?: string; // optional photo URL
}

// SVG-based product photos generated inline - lightweight and reliable
// Each product gets a unique SVG photo with brand colors and branding
export const productIconMap: Record<string, ProductVisual> = {
  netflix: { emoji: '🎬', gradient: 'from-red-700 via-red-900 to-black', bgColor: '#141414', accent: '#E50914' },
  spotify: { emoji: '🎵', gradient: 'from-green-600 via-green-800 to-black', bgColor: '#121212', accent: '#1DB954' },
  steam: { emoji: '🎮', gradient: 'from-slate-700 via-slate-900 to-black', bgColor: '#1b2838', accent: '#66c0f4' },
  google: { emoji: '🔷', gradient: 'from-blue-600 via-green-600 to-yellow-500', bgColor: '#202124', accent: '#4285F4' },
  playstation: { emoji: '🕹️', gradient: 'from-blue-700 via-indigo-800 to-black', bgColor: '#003791', accent: '#0070D1' },
  xbox: { emoji: '🎯', gradient: 'from-green-600 via-emerald-800 to-black', bgColor: '#107C10', accent: '#107C10' },
  deezer: { emoji: '🎧', gradient: 'from-pink-600 via-purple-700 to-black', bgColor: '#000000', accent: '#FE2B5B' },
  pubg: { emoji: '🔫', gradient: 'from-orange-600 via-amber-700 to-red-900', bgColor: '#2a1810', accent: '#F2A900' },
  freefire: { emoji: '🔥', gradient: 'from-amber-500 via-orange-600 to-red-700', bgColor: '#1a0f0a', accent: '#FF6B00' },
  windows: { emoji: '🪟', gradient: 'from-sky-500 via-blue-700 to-indigo-900', bgColor: '#0078D4', accent: '#0078D4' },
  office: { emoji: '📊', gradient: 'from-orange-500 via-red-600 to-red-800', bgColor: '#181818', accent: '#D83B01' },
  apple: { emoji: '🍎', gradient: 'from-gray-500 via-gray-700 to-black', bgColor: '#000000', accent: '#A2AAAD' },
};
